jobs:

- job: gate
  steps:
  - bash: |
      echo "IS_FORK: $IS_FORK"
      if [ $IS_FORK != 'False' ] ; then
        exit 1
      fi
    env:
      IS_FORK: '$(System.PullRequest.IsFork)'
    displayName: 'No remote PRs'

- job: fats
  dependsOn: gate

  # don't run for pull requests
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  strategy:
    matrix:
      kind:
        imageName: ubuntu-16.04
        qualifier: kind
        cluster: kind
        registry: docker-daemon
      dockerhub:
        imageName: ubuntu-16.04
        qualifier: dockerhub
        cluster: kind
        registry: dockerhub
      gke:
        imageName: ubuntu-16.04
        qualifier: gke
        cluster: gke
        registry: gcr
      pks:
        imageName: ubuntu-16.04
        qualifier: pks
        cluster: pks-gcp
        registry: gcr
      windows:
        imageName: windows-2019
        qualifier: windows
        cluster: gke
        registry: gcr

  timeoutInMinutes: 90

  pool:
    vmImage: $(imageName)

  variables:
    CLUSTER:  '$(cluster)'
    REGISTRY: '$(registry)'
    CLUSTER_NAME: 'fats-$(Build.BuildId)-$(qualifier)'
    NAMESPACE: '$(CLUSTER_NAME)'

  steps:

  - task: DownloadSecureFile@1
    inputs:
      secureFile: toolsmiths-pks15.json
    condition: and(succeeded(), eq(variables['CLUSTER'], 'pks-gcp'))
    displayName: 'Load credentials'

  - bash: ./ci/run.sh
    env:
      DOCKER_USERNAME: '$(DockerUsername)'
      DOCKER_PASSWORD: '$(DockerPassword)'
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
      PIVNET_REFRESH_TOKEN: '$(PivnetRefreshToken)'
    displayName: 'Run FATS'

  - bash: ./diagnostics.sh
    timeoutInMinutes: 1
    continueOnError: true
    displayName: 'Dump diagnostics'
  - template: ci/dump-diagnostics-steps.yml

  - bash: ./ci/cleanup.sh
    env:
      DOCKER_USERNAME: '$(DockerUsername)'
      DOCKER_PASSWORD: '$(DockerPassword)'
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
      PIVNET_REFRESH_TOKEN: '$(PivnetRefreshToken)'
    condition: always()
    displayName: 'Cleanup FATS'
