pr: none

variables:
  DOCKER_USERNAME: '$(DockerUsername)'
  DOCKER_PASSWORD: '$(DockerPassword)'
  GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
  PIVNET_REFRESH_TOKEN: '$(PivnetRefreshToken)'

jobs:
- job: fats

  strategy:
    matrix:
      minikube:
        imageName: ubuntu-16.04
        cluster: minikube
        registry: dockerhub
      gke:
        imageName: ubuntu-16.04
        cluster: gke
        registry: gcr
      pks:
        imageName: ubuntu-16.04
        cluster: pks-gcp
        registry: gcr
      windows:
        imageName: windows-2019
        cluster: gke
        registry: gcr

  timeoutInMinutes: 90

  pool:
    vmImage: $(imageName)

  variables:
    CLUSTER:  '$(cluster)'
    REGISTRY: '$(registry)'
    CLUSTER_NAME: 'fats-$(Build.BuildId)-$(Agent.JobName)'
    NAMESPACE: '$(CLUSTER_NAME)'

  steps:

  - script: sudo apt-get update && sudo apt-get remove moby-engine moby-cli && sudo apt-get install docker.io=18.06.1-0ubuntu1.2~16.04.1
    condition: |
      and(
        succeeded(),
        eq(variables['CLUSTER'], 'minikube'),
        ne(variables['Agent.OS'], 'Windows_NT')
      )
    displayName: 'Downgrade Docker'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: toolsmiths-healdsburg.json
    condition: and(succeeded(), eq(variables['CLUSTER'], 'pks-gcp'))
    displayName: 'Load credentials'

  - bash: ./tests/run.sh
    displayName: 'Run FATS'

  - bash: ./tests/cleanup.sh
    condition: always()
    displayName: 'Cleanup FATS'
