pr: none

jobs:
- job: fats

  strategy:
    matrix:
      minikube:
        imageName: ubuntu-16.04
        qualifier: minikube
        cluster: minikube
        registry: dockerhub
      daemonregistry:
        imageName: ubuntu-16.04
        qualifier: daemonregistry
        cluster: minikube
        registry: docker-daemon
      gke:
        imageName: ubuntu-16.04
        qualifier: gke
        cluster: gke
        registry: gcr
      # TODO restore PKS
      # pks:
      #   imageName: ubuntu-16.04
      #   qualifier: pks
      #   cluster: pks-gcp
      #   registry: gcr
      # TODO restore windows support once we have a linux docker daemon available
      # windows:
      #   imageName: windows-2019
      #   qualifier: windows
      #   cluster: gke
      #   registry: gcr

  timeoutInMinutes: 90

  pool:
    vmImage: $(imageName)

  variables:
    CLUSTER:  '$(cluster)'
    REGISTRY: '$(registry)'
    CLUSTER_NAME: 'fats-$(Build.BuildId)-$(qualifier)'
    NAMESPACE: '$(CLUSTER_NAME)'

  steps:

  - script: sudo apt-get update && sudo apt-get remove moby-engine moby-cli && sudo apt-get install docker.io=18.06.1-0ubuntu1.2~16.04.1
    condition: |
      and(
        succeeded(),
        eq(variables['CLUSTER'], 'minikube'),
        ne(variables['Agent.OS'], 'Windows_NT')
      )
    displayName: 'Downgrade Docker'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: toolsmiths-sandcity.json
    condition: and(succeeded(), eq(variables['CLUSTER'], 'pks-gcp'))
    displayName: 'Load credentials'

  - bash: ./tests/run.sh
    env:
      DOCKER_USERNAME: '$(DockerUsername)'
      DOCKER_PASSWORD: '$(DockerPassword)'
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
      PIVNET_REFRESH_TOKEN: '$(PivnetRefreshToken)'
    displayName: 'Run FATS'

  - bash: ./tests/cleanup.sh
    env:
      DOCKER_USERNAME: '$(DockerUsername)'
      DOCKER_PASSWORD: '$(DockerPassword)'
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
      PIVNET_REFRESH_TOKEN: '$(PivnetRefreshToken)'
    condition: always()
    displayName: 'Cleanup FATS'
